# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b5fdcd34a7ddbffa5dde1b5036f39f7086b4fa9050dd1fa335bae3dac13040cf6a42bd1a86d2c984eda1ad73974455ebfb33b6123510f8949aa7a77c618cdf

test:
  secret_key_base: bf7e12a32c542a2769905b1f7e5e6e508486dbf065a22c6307b4d1a54d83cce4ca398ee6195c1c832ec576270310cdccc9c7cfc401f668f0fba4c6728e553bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
