app:
  build: ./
  container_name: app
  ports:
    - "80:80"
  environment:
      LOCAL_DEV: "false" # true or false. Domain is l.com and la.com
  working_dir: "/app"
  volumes:
    - "/app"
    - "/usr/local/bundle"
  command: "/bin/bash /start.sh"
  tty: true
