app:
  build: ./
  container_name: app
  ports:
    - "80:80"
    - "443:443"
    - "3000:3000"
  environment:
      LOCAL_DEV: "false" # true or false. Domain is l.com and la.com
  working_dir: "/app"
  volumes:
    # - "./data:/app"
    - "./nginx.conf:/etc/nginx/nginx.conf"
    - "./start.sh:/start.sh"
  # command: "/bin/bash /start.sh"
  command: "/bin/bash"
  tty: true
  links:
      - db:db


db:
  image: mariadb
  container_name: db
  command: mysqld
  ports:
    - "3306"
  volumes:
    - "/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "rails"
    MYSQL_DATABASE: "rails"
